name: "Immich Public Proxy"
version: "1.15.1-ha1"
slug: "immich_public_proxy"
description: "A secure public proxy for Immich"
url: "https://github.com/malrogers7/ha-apps/tree/main/immich-public-proxy"
arch:
  - amd64  
  - aarch64
startup: application
boot: auto
watchdog: "http://[HOST]:[PORT:3000]/share/healthcheck"
options:
  immich_url: "http://internal-ip:2283"
  public_url: "https://photos.yourdomain.com"
  single_image_gallery: false
  download_original: true
  downloaded_filename: 0
  show_gallery_title: true
  allow_download_all: 1
  show_home_page: true
  show_image_description: true
schema:
  immich_url: url
  public_url: url
  single_image_gallery: bool
  download_original: bool 
  downloaded_filename: "list(original_name|immich_id|short_id)"
  show_gallery_title: bool
  allow_download_all: "list(disabled|per_share|always)"
  show_home_page: bool
  show_image_description: bool
ports:
  3000/tcp: 3000
