name: "Immich Public Proxy"
version: "1.0.0"
slug: "immich_public_proxy"
description: "A secure public proxy for Immich"
url: "https://github.com/malrogers7/ha-addons/"
arch:
  - amd64  
  - aarch64
startup: application
boot: auto
options:
  immich_url: "http://192.168.1.X:2283"
  public_url: "https://photos.yourdomain.com"
schema:
  immich_url: url
  public_url: url
ports:
  3000/tcp: 3000 # Maps container port 3000 to host port 3000
map:
  - config:rw # Optional: if the app needs to save config files
