name: "Immich Public Proxy"
version: "1.0.0"
slug: "immich_public_proxy"
description: "A secure public proxy for Immich"
url: "https://github.com/malrogers7/ha-addons/"
arch:
  - amd64  
  - aarch64
startup: application
boot: auto
options:
  immich_url: "http://internal-ip:2283"
  public_url: "https://photos.yourdomain.com"
  single_image_gallery: false
  download_original: true
  downloaded_filename: 0
  show_gallery_title: true
  allow_download_all: 1
  show_home_page: true
  show_image_description: true
schema:
  immich_url: url
  public_url: url
  single_image_gallery: bool
  download_original: bool
  downloaded_filename: "list(0|1|2)" # Creates a dropdown
  show_gallery_title: bool
  allow_download_all: "list(0|1|2)"
  show_home_page: bool
  show_image_description: bool
ports:
  3000/tcp: 3000 # Maps container port 3000 to host port 3000
map:
  - config:rw # Optional: if the app needs to save config files
