name: "Authentik"
version: "2024.12.0-d"
slug: "authentik"
description: "Full Authentik stack (App + Redis + Postgres) in one container."
arch:
  - aarch64
  - amd64
ports:
  9000/tcp: 9000
  9443/tcp: 9443
map:
  - config:rw
  - share:rw 
options:
  secret_key: "CHANGE_ME_PLEASE_TO_SOMETHING_RANDOM"
schema:
  secret_key: str
  
# Enable the Ingress feature
ingress: true
ingress_port: 9000

# Add Authentik to the sidebar
panel_icon: mdi:shield-account
panel_title: "Authentik"
panel_admin: true

environment:
  AUTHENTIK_TRUSTED_PROXIES: "172.30.32.2"
  AUTHENTIK_LISTEN__HTTP: "0.0.0.0:9000"
