name: "Authentik"
version: "2024.12.0-i"
slug: "authentik"
description: "Full Authentik stack (App + Redis + Postgres) in one container."
webui: http://[HOST]:[PORT:9000]
arch:
  - aarch64
  - amd64
ports:
  9000/tcp: 9000
  9443/tcp: 9443
map:
  - config:rw
  - share:rw 
schema:
  secret_key: str
