name: "Authentik"
version: "2024.12.0-a"
slug: "authentik"
description: "Full Authentik stack (App + Redis + Postgres) in one container."
arch:
  - aarch64
  - amd64
ports:
  9000/tcp: 9000
  9443/tcp: 9443
map:
  - config:rw
  - share:rw 
options:
  secret_key: "CHANGE_ME_PLEASE_TO_SOMETHING_RANDOM"
schema:
  secret_key: str
